### ISSUE TITLE
Nginx 环境部署后报错 404

### ISSUE THREAD

**Issue by 3esmile** [helei112g/payment#25]
你好
今天在部署payment 2 到 nginx 服务器上的时候，出现404报错，
我用的是代码里面 /examples/charge.php 测试的，在本地上运行正常，可以正常返回。
把文件上传到服务器上后却会有问题（没有改动任何代码）。
不知您是否有空帮忙看下是什么问题？
谢谢！

以下是错误提示：
```
Fatal error: Uncaught Error: Call to undefined function Payment\Common\Ali\Data\Charge\bccomp() in /var/www/<project_folder>/vendor/riverslei/payment/src/Common/Ali/Data/Charge/ChargeBaseData.php:89 Stack trace: 
#0 /var/www/<project_folder>/vendor/riverslei/payment/src/Common/BaseData.php(43): Payment\Common\Ali\Data\Charge\ChargeBaseData->checkDataParam() 

#1 /var/www/<project_folder>/vendor/riverslei/payment/src/Common/Ali/AliBaseStrategy.php(66): Payment\Common\BaseData->__construct(Object(Payment\Common\AliConfig), Array) 

#2 /var/www/<project_folder>/vendor/riverslei/payment/src/ChargeContext.php(121): Payment\Common\Ali\AliBaseStrategy->handle(Array)

#3 /var/www/<project_folder>/vendor/riverslei/payment/src/Client/Charge.php(55): Payment\ in /var/www/<project_folder>/vendor/riverslei/payment/src/Common/Ali/Data/Charge/ChargeBaseData.php on line 89
```

**Comment by 3esmile** [comment]
@helei112g @nihaibao 
请大神指教，目前项目卡在这里，后续工作无法开展。
万分感谢！

**Comment by 3esmile** [comment]
找到问题了。不好意思 打扰了。
是因为服务器没有 bcmath 模块，安装一下就好了。

`yum install php70u-bcmath -y`

**Comment by helei112g** [comment]
推荐使用 3.x 版本。功能更多。
